### PR TITLE
Lower the minimum sdk version to 2.1 for compatibility with Flutter

### PR DESCRIPTION
**Pull request by touhonoob**

### CODE REVIEW

**Comment by kevmoo** [comment]
@touhonoob – which version of Flutter are you on? Latest should be on 2.2...at least

**Comment by touhonoob** [comment]
@kevmoo I am using stable channel v1.2.1

```
> flutter upgrade
Upgrading Flutter
From https://github.com/flutter/flutter
   c42f3fb1d..6a250c8d6  master     -> origin/master
Already up-to-date.

Upgrading engine...
Already up-to-date.

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (3 months ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by kevmoo** [comment]
Can I suggest switching to the dev channel? 😄

**Comment by kevmoo** [comment]
You won't have to wait very long for stable to be updated... 😉

**Comment by kevmoo** [comment]
Well. Ugh. I like testing on oldest supported. But the issue is only in the example. K...

**Comment by kevmoo** [comment]
Update the changelog – I have an entry for the SDK

**Comment by touhonoob** [comment]
@kevmoo Changelog updated. I am using this for a Flutter package, so requiring dev channel might be problematic for package users.

**Comment by JaceHensley** [comment]
Can this be published to pub? Trying to publish the package that needs this and `publish --dry-run` is warning about publishing with a git dependency. Thanks!

**Comment by kevmoo** [comment]
1.1.1 is out!

**Pull request merged**
