### PR TITLE
Expose maskPattern to the User as make([int? maskPattern])

### PR DESCRIPTION
**Pull request by Grooviz**
Closes https://github.com/kevmoo/qr.dart/issues/39

### CODE REVIEW

**Comment by kevmoo** [comment]
Please add an entry to the changelog – this would be version 1.4

**Comment by kevmoo** [comment]
...and update the pubspec, too!

**Comment by Grooviz** [comment]
I updated the CHANGELOG.

For the pubspec.yaml, you already specified the version as version:
2.0.0-nullsafety.
Do you want me to overwrite this change back to version: 1.4.0?

Regards,

Thierry

**Comment by kevmoo** [comment]
Oh no!

It should go under 2.0.0-nullsafety.1 – now

**Comment by Grooviz** [comment]
Done!

**Pull request merged**
